// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkxkbEawaT2tkrGvAfV2a4GT-MyPajERE',
    appId: '1:885476909974:web:1793157e103816d67fb3b7',
    messagingSenderId: '885476909974',
    projectId: 'swiftserve-production',
    authDomain: 'swiftserve-production.firebaseapp.com',
    storageBucket: 'swiftserve-production.firebasestorage.app',
    measurementId: 'G-344077ST4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXLVJAeyXT6vBkmRxE2ku1WbNQ_XQAcY4',
    appId: '1:885476909974:android:5e17d1166ff278827fb3b7',
    messagingSenderId: '885476909974',
    projectId: 'swiftserve-production',
    storageBucket: 'swiftserve-production.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYFRtSgo2v0YzZZX3Z8_zumIVtvBHRgJQ',
    appId: '1:885476909974:ios:cafbd62abac1dde27fb3b7',
    messagingSenderId: '885476909974',
    projectId: 'swiftserve-production',
    storageBucket: 'swiftserve-production.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYFRtSgo2v0YzZZX3Z8_zumIVtvBHRgJQ',
    appId: '1:885476909974:ios:cafbd62abac1dde27fb3b7',
    messagingSenderId: '885476909974',
    projectId: 'swiftserve-production',
    storageBucket: 'swiftserve-production.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkxkbEawaT2tkrGvAfV2a4GT-MyPajERE',
    appId: '1:885476909974:web:0f900945f2e9f65f7fb3b7',
    messagingSenderId: '885476909974',
    projectId: 'swiftserve-production',
    authDomain: 'swiftserve-production.firebaseapp.com',
    storageBucket: 'swiftserve-production.firebasestorage.app',
    measurementId: 'G-851QE9KRY2',
  );
}
