// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC-FuZOYl_0B0EpEJnP-i-4LlRwqqwYVA',
    appId: '1:538889401922:web:39f92f6182d7435ea89fdb',
    messagingSenderId: '538889401922',
    projectId: 'swiftserve-f9fe6',
    authDomain: 'swiftserve-f9fe6.firebaseapp.com',
    storageBucket: 'swiftserve-f9fe6.firebasestorage.app',
    measurementId: 'G-Y17H6HLNX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvkyQyJYQxTA6D4hfCg-NWMf1jaLtQ7bk',
    appId: '1:538889401922:android:95aa11fa5d3bb23ca89fdb',
    messagingSenderId: '538889401922',
    projectId: 'swiftserve-f9fe6',
    storageBucket: 'swiftserve-f9fe6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6pGv7PVIRV5umPG_KL9Py-6ZykksIfGQ',
    appId: '1:538889401922:ios:0833835301dba7c0a89fdb',
    messagingSenderId: '538889401922',
    projectId: 'swiftserve-f9fe6',
    storageBucket: 'swiftserve-f9fe6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
